# num_branches: 1
# feature_dims: [6]
# num_branches: 1
# feature_dims: [30]
# num_branches: 2
# feature_dims: [30, 36]
# num_branches: 2
# feature_dims: [36, 6]
# num_branches: 2
# feature_dims: [30, 6]
num_branches: 3
feature_dims: [30, 36, 6]
activation_function: relu
optimizer: adam
dropout: 0.2
learning_rate: 0.0003
batch_size: 2048